### PR TITLE
Add empty modifier

### PR DESCRIPTION
**Pull request by jcconnell**
Adds ability to set a field to it's zero value.

### CODE REVIEW

**Comment by jcconnell** [comment]
I see that there are now some conflicts to resolve, but any thoughts on this otherwise?

**Comment by deankarn** [comment]
I’m curious tour use case for this because Go by default will already have the default value of the data type set by design eg. No such thing as uninitialized value if Go

**Comment by jcconnell** [comment]
Maybe I am going about this wrong but here's what I've done and why I think this will help. I need to store a struct with sensitive fields. First, I do field level encryption and store a byte representation of the struct. Then I do field level sanitization and store a string/JSONB version of the struct. 

**Process**
* Encrypt sensitive fields
* Marshall and store the bytes
* Sanitize the sensitive fields (fields are now encrypted)
* Marshall and store the bytes

After encryption, sensitive fields will contain values like the following: `\u0001\u0002\u0002\u0000x]\ufffd\ufffd\r\ufffd\u001fˊE\uff...`

I hoped that `mod:"default=example"` would work, but the encrypted values remain in the field
```go
type example struct {
    AccountNumber        string `mod:"default=redacted"`
}
```

Instead, I had to use the following
```go
type example struct {
    AccountNumber        string `mod:"strip_alpha,strip_num,strip_alpha_unicode,strip_num_unicode"`
}
```

The goal with this PR was to have the ability to set the field to it's empty value.

**Comment by deankarn** [comment]
Ag I see @jcconnell its to reset something that was already set, that makes more sense.

ya the reason default=redacted doesn’t work is because it will only set the value IF there isn’t one already aka will only set when is the default value currently.

Im willing to merge then nice! Pleas ebe patient been super busy lately.

also question: do you think it would be valuable to have another tag that like default=… but would set a value no matter what? Maybe called set lol

**Comment by jcconnell** [comment]
Ahhh, I see why `default=redacted` didn't work! I think I misunderstood the description then.  `set` seems like a reasonable addition to me. 

So something like below? 
* `set`: set a field to a value regardless of state (struct is populated)
* `default`: set a field to a value only if it hasn't been set (struct is empty)
*  `empty`: set a field to it's default value regardless of state (struct is populated)

**Review by deankarn — APPROVED** [review]

**Pull request merged**
